{
  # parallelism settings
  "pipe-parallel-size": 1,
  "model-parallel-size": 1,

  # model settings, 162,322,944 parameters
  "num-layers": 12,
  "hidden-size": 768,
  "num-attention-heads": 12,
  "seq-length": 1024,
  "max-position-embeddings": 1024,
  "pos-emb": "rotary",
  "rotary-pct": 0.25,
  "no-weight-tying": true,
  "gpt-j-residual": true,
  "output-layer-parallelism": "column",
  
  "attention-config": [[["flash"], 12]],

  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.0001,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  # batch size (training on 1 gpu, takes up 37.5Gb of memory)
  "train_batch_size": 480,
  "train_micro_batch_size_per_gpu": 60,
  "gradient_accumulation_steps": 8,
  "data-impl": "mmap",
  "num_workers": 1,

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "train-iters": 100000,
  "lr-decay-iters": 100000,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 1000,
  "eval-interval": 1000,
  "eval-iters": 10,

  "log-interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  "train-data-paths": ["data/openwebtext-processed_text_document"],
  "valid-data-paths": ["data/openwebtext-processed_text_document"],
  "test-data-paths": ["data/openwebtext-processed_text_document"],

  "tokenizer-type": "GPT2BPETokenizer",
  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",

  "use_wandb": true,
  "wandb_project": "neox",
  "wandb_group": "alon_config_small",

  # to use a single GPU
  # "include": "localhost:7",
  # "world_size": 1,
}